import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Clients | Family Services',
  description: 'Generated by create next app',
};

const Clients = () => {
  return (
    <div className="">
      <p className="">Clients</p>
    </div>
  );
};

export default Clients;
