import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Frais Km | Family Services',
  description: 'Generated by create next app',
};

const Frais = () => {
  return (
    <div className="">
      <p className="">Frais Km</p>
    </div>
  );
};

export default Frais;
